### ISSUE TITLE
TorchDynamo sometime takes very long to symbolically interpret stackframes.

### ISSUE THREAD

**Issue by Chillee** [pytorch/torchdynamo#525] opened 2022-07-07 23:25 UTC
Looking at Bram's example

Example accessible internally: https://www.internalfb.com/phabricator/paste/view/P514325083

From @voznesenskym 

> Anyway, can confirm it super slow, can confirm it does not get past the first for loop, hanging on Y, dot = m(X_ref). Not sure if its hanging, as adding this in the NandNet forward:

> So its not hanging, but it certainly seems to be adding a ton of overhead and needing some special finagling,

**Comment by anijain2305** [comment] 2022-08-30 17:48
cc @wconstab Lets use your timers to diagnose this.

**Comment by wconstab** [comment] 2022-08-31 00:10
I've taken a look and found that this model is spending a lot of time in dynamo instruction translation.  I added some timing code to the translator and produced this chart of the time spent so far (it's streaming out data but not sure how far along it is, hasn't finished an iteration yet)

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/4984825/187564982-15c00a0b-fb09-4675-9914-876bc7c28b8f.png">

will spend some more time thinking about how to instrument what's going on in call_function and see if there is anything we can do to speed it up

**Comment by wconstab** [comment] 2022-08-31 00:47
The overall structure of this model's forward() is to iterate over 21 layers, and inside each layer iterate over N sub-layers where N is related to the layer index.  So it's roughly an N^2 problem but its only about 400 inner loops, so that should hopefully be handleable.

Backward seems to be quite fast, which aligns with the issues coming from translation rather than compilation.

Optimizer is again quite slow, even slower than .forward()-
We fail the 'capturable' check in adam optimizer (due to not being on cuda) and take a [path the results in `.item()` calls](https://github.com/pytorch/pytorch/blob/master/torch/optim/adam.py#L309) for each of the model's many (hundreds) of parameters.  This causes a lot of dynamo graph breaks while trying to capture the optimizer.

**Comment by voznesenskym** [comment] 2022-08-31 00:53
> The overall structure of this model's forward() is to iterate over 21 layers, and inside each layer iterate over N sub-layers where N is related to the layer index. So it's roughly an N^2 problem but its only about 400 inner loops, so that should hopefully be handleable.
> 
> Backward seems to be quite fast, which aligns with the issues coming from translation rather than compilation.
> 
> Optimizer is again quite slow, even slower than .forward()- We fail the 'capturable' check in adam optimizer (due to not being on cuda) and take a [path the results in `.item()` calls](https://github.com/pytorch/pytorch/blob/master/torch/optim/adam.py#L309) for each of the model's many (hundreds) of parameters. This causes a lot of dynamo graph breaks while trying to capture the optimizer.

can you enable capture for .item()? `config.capture_scalar_outputs = True` and see? Might help a bit...

**Comment by wconstab** [comment] 2022-08-31 01:07
Moving the optimizer.step() call "left" (e.g. outdenting it from the `with optimize()` scope and avoiding dynamo'ing it)  results in this performance profile, which is a big improvement.  It is still a very slow compile for the first iteration, but then it starts to zip along 
```
0%|                                                                   | 0/10001 [00:00<?, ?it/s]
forward time 350.1971745491028, backward time 0.19413161277770996, opt time 0.04160618782043457
loss: 7.66e-01:   0%|                                     | 1/10001 [06:17<1047:56:04, 377.26s/it]
forward time 0.07477617263793945, backward time 0.1949005126953125, opt time 0.035239219665527344
loss: 7.66e-01:   0%|                                      | 2/10001 [06:17<431:57:41, 155.52s/it]
forward time 0.0757603645324707, backward time 0.19508600234985352, opt time 0.03519153594970703
loss: 7.66e-01:   0%|                                       | 3/10001 [06:17<235:05:10, 84.65s/it]
```
I will post the timing with `config.capture_scalar_outputs = True` but it is going to take a while

**Comment by wconstab** [comment] 2022-08-31 05:19
no luck with that option:
```
----------------------------------------                                                          TORCHDYNAMO: backend compiler failed                                         
Traceback (most recent call last):                                
  File "/scratch/whc/work/torchdynamo/torchdynamo/output_graph.py", line 392, in call_user_compile
r               
    compiled_fn = self.compiler_fn(gm, self.example_inputs())                           
  File "/scratch/whc/work/torchdynamo/torchdynamo/optimizations/training.py", line 34, in compile_
fn                                                                                       
    return cls(gm, example_inputs).verified_candidate()
  File "/scratch/whc/work/torchdynamo/torchdynamo/optimizations/training.py", line 75, in __init__
    mutated = has_mutation(self.gm, self.example_inputs, inputs_only=True)        
  File "/scratch/whc/work/torchdynamo/torchdynamo/optimizations/training.py", line 84, in example_
inputs                                                                   
    return clone_inputs(self.original_example_inputs)                                             
  File "/scratch/whc/work/torchdynamo/torchdynamo/utils.py", line 372, in clone_inputs     
    res[i] = clone_input(res[i])                             
  File "/scratch/whc/work/torchdynamo/torchdynamo/utils.py", line 343, in clone_input             
    result.copy_(x.clone())                  
  File "/scratch/whc/work/pytorch/torch/_subclasses/fake_tensor.py", line 470, in __torch_dispatch
__                                                                                                
    return func(*args, **kwargs)                                                                  
  File "/scratch/whc/work/pytorch/torch/_ops.py", line 60, in __call__                            
    return self._op(*args, **kwargs or {})                                                          File "/scratch/whc/work/pytorch/torch/utils/_python_dispatch.py", line 74, in wrapped           
    return f(self, *args, **kwargs)                                                   
  File "/scratch/whc/work/pytorch/torch/_subclasses/fake_tensor.py", line 679, in __torch_dispatch__                                                                                   
    raise Exception(                                 
Exception: Invoking operators with non-Fake Tensor inputs in FakeTensorMode is not yet supported. 
Please convert all Tensors to FakeTensors first. Found in aten.copy_.default(*(tensor([ 7.3138e+31
,  3.0880e-41,  3.5939e+16,  3.0880e-41, -6.2314e-07,                                             
        -7.9598e-07, -5.9660e-07]), FakeTensor(<torch._subclasses.fake_tensor.FakeTensorMode objec
t at 0x7fccb92eda30>, FakeTensor(..., device='meta', size=(7,)), cpu)), **{})            
----------------------------------------                                                          
torchdynamo.convert_frame: [ERROR] WON'T CONVERT step /scratch/whc/work/pytorch/torch/optim/adam.p
y line 109                                                                                        
due to:                                                                                           
Traceback (most recent call last):                                        
  File "/scratch/whc/work/pytorch/torch/_subclasses/fake_tensor.py", line 679, in __torch_dispatch__                                                                                                
    raise Exception(                                 
Exception: Invoking operators with non-Fake Tensor inputs in FakeTensorMode is not yet supported. Please convert all Tensors to FakeTensors first. Found in aten.copy_.default(*(tensor([ 7.3138e+31
,  3.0880e-41,  3.5939e+16,  3.0880e-41, -6.2314e-07,                                
        -7.9598e-07, -5.9660e-07]), FakeTensor(<torch._subclasses.fake_tensor.FakeTensorMode object at 0x7fccb92eda30>, FakeTensor(..., device='meta', size=(7,)), cpu)), **{})
        ```

**Comment by mlazos** [comment] 2022-08-31 18:34
I have plans to change the assertion to only require all tensors be on the same device (vs on cuda) in Adam so that we can set `capturable=True`. This avoids the calls to `item()` entirely.

**Comment by mlazos** [comment] 2023-01-23 20:57
Confirmed that this is resolved with https://github.com/pytorch/torchdynamo/issues/1803

**Closed by mlazos** 2023-01-23 20:57 UTC
Labels: bad-ux, vertical:internal, dynamo
