### ISSUE TITLE
TorchBench training error: yolov3 : not converging

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#1352] opened 2022-09-26 14:58 UTC
Repro:
```
benchmarks/torchbench.py -d cuda --inductor --training --float32 --accuracy --no-skip --only yolov3
```

Test ran for a long time, but I didn't wait to see if it eventually ends.

**Comment by anijain2305** [comment] 2022-09-28 19:00
@yanboliang Can you take a look here? It unclear if its hanging or just taking very long to run.

**Comment by anijain2305** [comment] 2022-10-10 03:46
Ping on this.

**Comment by yanboliang** [comment] 2022-10-12 06:03
I spent the past two days debug this issue and found the model is hanging not taking very long to run. When it hit [this line](https://github.com/pytorch/torchdynamo/blob/main/torchinductor/compile_fx.py#L103), it's stuck. I was trying different way to find the root cause and it seems we stuck when ```args``` of a ```aten.add.Tensor``` target when run this graph. But I didn't have further progress yet. 
However, when I was feeling hopeless, I started to play around this model under different configs. After I upgraded to the most updated dependencies, I found there is an error rather than hanging. The error is:
```
TorchDynamo optimized model failed to run because of following error
ERROR:common:function takes exactly 11 arguments (14 given)
Traceback (most recent call last):
  File "/scratch/ybliang/work/repos/torchdynamo/benchmarks/common.py", line 1136, in check_accuracy
    new_result = optimized_model_iter_fn(model, example_inputs)
  File "/scratch/ybliang/work/repos/torchdynamo/torchdynamo/eval_frame.py", line 175, in _fn
    return fn(*args, **kwargs)
  File "/scratch/ybliang/work/repos/torchdynamo/benchmarks/torchbench.py", line 324, in forward_and_backward_pass
    def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
  File "/scratch/ybliang/work/repos/torchdynamo/benchmarks/torchbench.py", line 325, in <graph break in forward_and_backward_pass>
    cloned_inputs = clone_inputs(inputs)
  File "/scratch/ybliang/work/repos/torchdynamo/benchmarks/torchbench.py", line 328, in <graph break in forward_and_backward_pass>
    pred = mod(*cloned_inputs)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/scratch/ybliang/work/repos/torchbenchmark/torchbenchmark/models/yolov3/yolo_models.py", line 235, in forward
    def forward(self, x, augment=False, verbose=False):
  File "/scratch/ybliang/work/repos/torchbenchmark/torchbenchmark/models/yolov3/yolo_models.py", line 265, in forward_once
    def forward_once(self, x, augment=False, verbose=False):
  File "/scratch/ybliang/work/repos/torchdynamo/torchdynamo/eval_frame.py", line 175, in _fn
    return fn(*args, **kwargs)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 812, in forward
    return compiled_f(
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 803, in new_func
    return compiled_fn(args)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 230, in g
    return f(*args)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 449, in compiled_function
    return CompiledFunction.apply(*remove_dupe_args(args))
  File "/scratch/ybliang/work/repos/torchdynamo/torchdynamo/eval_frame.py", line 175, in _fn
    return fn(*args, **kwargs)
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 416, in forward
    fw_outs = call_func_with_args(
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 252, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/scratch/ybliang/work/env/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 230, in g
    return f(*args)
  File "/scratch/ybliang/work/repos/torchdynamo/torchinductor/compile_fx.py", line 167, in run
    return model(*new_inputs)
  File "/scratch/ybliang/work/repos/torchdynamo/torchinductor/compile_fx.py", line 184, in run
    compiled_fn = cudagraphify_impl(model, new_inputs, static_input_idxs)
  File "/scratch/ybliang/work/repos/torchdynamo/torchinductor/compile_fx.py", line 241, in cudagraphify_impl
    model(*static_inputs)
  File "/tmp/torchinductor_ybliang/nn/cnn67dfsjvrkwzqd7afzoezikqjj7tmr4uqhhig5m2p2ejekg5cy.py", line 7992, in call
    kernel0.run(buf0, buf1, 512, 24576, grid=grid(512), stream=stream0)
  File "/scratch/ybliang/work/repos/torchdynamo/torchinductor/triton_ops/autotune.py", line 157, in run
    return launcher(
  File "<string>", line 4, in launcher
TypeError: function takes exactly 11 arguments (14 given)
FAIL
```
It seems this is an obvious error, however, I think this is another irrelevant bug. As if I switch to ```-d cpu```, it's still hanging rather than throwing error.

**Comment by anijain2305** [comment] 2022-10-13 00:18
It fails because of `max_pool2d_with_indices_backward`

~~~
from math import inf

import torch
import torch.fx as fx
from torch import device
from torch import tensor
from torch.fx.experimental.proxy_tensor import make_fx
from torch.nn import *

from torchdynamo.testing import rand_strided

# torch version: 1.14.0a0+git25725fd
# torch cuda version: 11.6
# torch git version: 25725fd62448165b91647304c26d676db22b6955


# CUDA Info:
# nvcc: NVIDIA (R) Cuda compiler driver
# Copyright (c) 2005-2022 NVIDIA Corporation
# Built on Thu_Feb_10_18:23:41_PST_2022
# Cuda compilation tools, release 11.6, V11.6.112
# Build cuda_11.6.r11.6/compiler.30978841_0

# GPU Hardware Info:
# NVIDIA A100-SXM4-40GB : 8


class Repro(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, add_319, where_54, getitem_5):
        max_pool2d_with_indices_backward = (
            torch.ops.aten.max_pool2d_with_indices_backward.default(
                add_319, where_54, [13, 13], [1, 1], [6, 6], [1, 1], False, getitem_5
            )
        )
        return (max_pool2d_with_indices_backward,)


a0 = torch.randn(torch.Size([2, 512, 12, 16]), dtype=torch.float32, device="cuda")
a1 = torch.randn(torch.Size([2, 512, 12, 16]), dtype=torch.float32, device="cuda")
a2 = torch.zeros(torch.Size([2, 512, 12, 16]), dtype=torch.int64, device="cuda")

args = (a0, a1, a2)
mod = make_fx(Repro().to(device="cuda"))(*args)

from torchinductor.compile_fx import compile_fx_inner

compiled = compile_fx_inner(mod, args)
res = compiled(*args)
~~~

**Comment by yanboliang** [comment] 2022-10-14 04:59
Update:

Obviously ```max_pool2d_with_indices_backward``` is the ops that doesn't work well, and the culprit is [this line](https://github.com/pytorch/torchdynamo/blob/65f680fa6b8b0c2323ff7118310e7241758781a3/torchinductor/lowering.py#L2468). According the implementation of ```ops.where```, every time ```gradient```(which is str) would be double size. And this is inside of a nested loop, the size of ```gradient``` can be huge if the kernel size if not small. E.g, in the above example, with kernel size = 13, the following are the size of ```gradient``` by GB:
```
0.000
0.000
0.000
0.000
0.000
0.000
0.000
0.001
0.001
0.002
0.004
0.009
0.018
0.035
0.070
0.141
0.282
0.564
1.127
2.255
4.510
9.020
18.039
36.078
72.156
144.313
288.626
Killed
```
The outer loop only iterates to 2, the size of ```gradient``` is 288 GB, and then killed by OS. 
About the solution, I think we need to find out a more efficient way to rewrite ```ops.where```. Otherwise, we can choose to fallback if kernel size > X.

@jansel @ngimel Let me know if you have any suggestion.

**Comment by ngimel** [comment] 2022-10-14 22:52
wdym `gradient` would be double in size? `ops.where` is simply `tl.where({a}, {b}, {c})`, how does the doubling happen?

**Comment by yanboliang** [comment] 2022-10-14 22:56
@ngimel Look at this line
```
gradient = ops.where(mask, ops.add(gradient, grad_part), gradient)
```
if the length of previous ```gradient``` is x, ```grad_part``` is y, the new ```gradient``` is ```tl.where(mask, x + y, x)```, which is > 2x.

**Comment by yanboliang** [comment] 2022-10-18 23:26
The root cause is we materialize the expr str at [this line](https://github.com/pytorch/pytorch/blob/master/torch/_inductor/dependencies.py#L238) when doing ```extract_read_writes```. Actually the code gen doesn't use this, so if I manually cut the expr str, the generated code still works well. I think the output of ```extract_read_writes``` only used for memory planning or scheduling, so it's fine to just clear it if it's too long? But in the long run, we should to rethink how to make the ```inner_fn``` of ```max_pool2d_with_indices_backward``` can convert to a more concise expr str. I'm giving a try at https://github.com/pytorch/pytorch/pull/87248, let me know if this looks good to you. @jansel

**Comment by yanboliang** [comment] 2022-10-25 05:21
This is fixed by https://github.com/pytorch/pytorch/pull/87248

**Closed by yanboliang** 2022-10-25 05:21 UTC
