### ISSUE TITLE
torchdynamo.reset doesn't work with inductor

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#1635] opened 2022-10-13 15:15 UTC
```
import torch
import torchdynamo

def test(a, b):
    return a + b

for i in range(3):
    opt_test = torchdynamo.optimize("inductor")(test)
    torchdynamo.reset()

print(opt_test(torch.rand(10), torch.rand(10)))
```

For this example, if we set a break point in compile_fx, we only hit it once instead of 3 times.

**Comment by sangongs** [comment] 2022-10-19 15:32
Isn't this an expected behavior? My understanding is that Dynamo compiles a function when the function is being invoked rather than being wrapped by `torchdynamo.optimize("inductor")`. Since `opt_test` is only called one time in `print()`, `compile_fx` is only called one time as well. If we put the print statement in the loop, `compile_fx()` is called 3 times:
 ```
import torch
import torch._dynamo as torchdynamo

def test(a, b):
    return a + b

for i in range(3):
    opt_test = torchdynamo.optimize("inductor")(test)
    print(opt_test(torch.rand(10), torch.rand(10)))
    torchdynamo.reset()
```

And if we comment out `torchdynamo.reset()` in the above program, `compile_fx()` is only called one time.

**Comment by sangongs** [comment] 2022-10-19 17:04
> I'd expect this to work. Reset should clear all caches (included the saved compiled function).

Yes, it does work. In @desertfire's program, `compile_fx` is called once because the function to be optimized is only called once.

**Comment by jansel** [comment] 2022-10-19 17:14
Isn't there a loop?  `for i in range(3):`

**Comment by sangongs** [comment] 2022-10-19 17:47
> Isn't there a loop? `for i in range(3):`

In the loop, the function `test` is just wrapped to `opt_test` by a `_TorchDynamoContext`. And `opt_test` is called outside the loop, where I believe the compilation happens.

**Comment by jansel** [comment] 2022-10-19 19:10
Oh right, my mistake
```
print(opt_test(torch.rand(10), torch.rand(10)))
```
needs to be inside the loop.

**Comment by sangongs** [comment] 2022-10-19 19:14
Yeah. If the print statement is in the loop, `compile_fx` does get called three times as expected.

So I guess we can close this issue?

**Comment by jansel** [comment] 2022-10-19 19:25
Yes, I believe so.  Thanks!

**Closed by jansel** 2022-10-19 19:25 UTC
