### ISSUE TITLE
Default graph break logs are too chatty

### ISSUE THREAD

**Issue by ezyang** [pytorch/torchdynamo#943] opened 2022-08-22 02:28 UTC
On master, on graph break I now get this message:

```
Torchdynamo: [WARNING] Graph break: call_function BuiltinVariable(print) [ConstantVariable(str)] {} from user code at:                         
   File "test/test_nn.py", line 22085, in <module>                                                                                             
    run_tests()                                                                                                                                
  File "/raid/ezyang/pytorch-scratch2/torch/testing/_internal/common_utils.py", line 792, in run_tests                                         
    unittest.main(argv=argv)                                                                                                                   
  File "/private/home/ezyang/Dev/pytorch-scratch2-env/lib/python3.8/unittest/main.py", line 101, in __init__                                   
    self.runTests()                                                                                                                            
  File "/private/home/ezyang/Dev/pytorch-scratch2-env/lib/python3.8/unittest/main.py", line 271, in runTests                                   
    self.result = testRunner.run(self.test)                                                                                                    
  File "/private/home/ezyang/Dev/pytorch-scratch2-env/lib/python3.8/unittest/runner.py", line 176, in run                                      
    test(result)                                                                                                                               
  File "/private/home/ezyang/Dev/pytorch-scratch2-env/lib/python3.8/unittest/suite.py", line 84, in __call__                                   
    return self.run(*args, **kwds)                                                                                                             
  File "/private/home/ezyang/Dev/pytorch-scratch2-env/lib/python3.8/unittest/suite.py", line 122, in run                                       
    test(result)                                                                                                                               
  File "/private/home/ezyang/Dev/pytorch-scratch2-env/lib/python3.8/unittest/case.py", line 736, in __call__                                   
    return self.run(*args, **kwds)                                                                                                             
  File "/raid/ezyang/pytorch-scratch2/torch/testing/_internal/common_device_type.py", line 437, in run                                         
    super().run(result=result)                                                                                                                 
  File "/raid/ezyang/pytorch-scratch2/torch/testing/_internal/common_utils.py", line 2030, in run                                              
    self._run_with_retry(                                                                                                                      
  File "/raid/ezyang/pytorch-scratch2/torch/testing/_internal/common_utils.py", line 1967, in _run_with_retry                                  
    super().run(result=result)                                                                                                                 
  File "/private/home/ezyang/Dev/pytorch-scratch2-env/lib/python3.8/unittest/case.py", line 676, in run                                        
    self._callTestMethod(testMethod)                                                                                                           
  File "/private/home/ezyang/Dev/pytorch-scratch2-env/lib/python3.8/unittest/case.py", line 633, in _callTestMethod                            
    method()                                                                                                                                   
  File "/raid/ezyang/pytorch-scratch2/torch/testing/_internal/common_device_type.py", line 377, in instantiated_test                           
    result = test(self, **param_kwargs)                                                                                                        
  File "/raid/ezyang/pytorch-scratch2/torch/testing/_internal/common_device_type.py", line 935, in dep_fn                                      
    return fn(self, *args, **kwargs)                                                                                                           
  File "test/test_nn.py", line 17341, in test_grid_sample_large_index_2d                                                                       
    @dtypes(torch.float, torch.double)                                                                                                         
  File "test/test_nn.py", line 17341, in test_grid_sample_large_index_2d                                                                       
    @dtypes(torch.float, torch.double)                                                                                                         
  File "test/test_nn.py", line 17363, in test_grid_sample_large_index_2d                                                                       
    print("before") 
```

The entire stack trace is too much. Users will think dynamo is broken. For each graph break there should only be one line for the warning by default.

**Comment by ezyang** [comment] 2022-08-22 02:28
cc @mlazos

**Comment by voznesenskym** [comment] 2022-08-22 02:41
#930

**Comment by ezyang** [comment] 2022-08-22 14:41
I have a patch that makes the stack trace shorter, but it seems like we are repeatedly warning about graph break *every* training iteration, which is bad; we should only complain about a given graph break once.

**Comment by jansel** [comment] 2022-08-22 16:30
Should we even complain once?  Or should this be behind a flag?

**Comment by soumith** [comment] 2022-08-22 16:39
this should be behind a flag before launch. but jason you said you wanted some kind of chatty stuff so that we can flag and fix issues in this phase.

**Comment by jansel** [comment] 2022-08-22 16:52
Most of the graphs break printouts I see running torchbench are:
1) numpy usage / copy.deepcopy / etc (third party libs)
2) .item() / .tolist() / etc
3) PyTorch functions we know cause graph breaks (e.g. `.backward()`)

None of these seem like issues needing flagging and fixing. Graph breaks caused by bugs (like exceptions) should definitely be printed out, but they are the minority.

**Comment by voznesenskym** [comment] 2022-08-22 16:53
> Should we even complain once? Or should this be behind a flag?

I'm workin a doc to for first time onboarding of a model + light explanation of what a graph break is. The rough story I am following is:

1) Run with nopython=True
2) if it breaks, run `.explain()` to find all the breaks
3) Profile performance, and close graph breaks and hopefully watch things get faster

For this flow, we don't really need that graph break on. I would also posit that almost none of our steady state engineering workflows (work on inductor, work on dynamo features, work on benchmarking) need to see the breaks. Only specific new integrations need it, or maybe if someone is explicitly hunting for breaks (and even then, I'd point to explain).

**Comment by mlazos** [comment] 2022-08-22 17:47
> I have a patch that makes the stack trace shorter, but it seems like we are repeatedly warning about graph break _every_ training iteration, which is bad; we should only complain about a given graph break once.

This seems to me like it is recompiling on every iteration then, this warning only gets printed during the compilation phase. I can look into only printing it once though, currently it will get printed during inline attempts as well.

**Comment by ezyang** [comment] 2022-08-22 18:41
OK, well we should figure out why it's trying to recompile every iteration too

**Comment by mlazos** [comment] 2022-09-22 00:26
Closing - graph breaks are only printed once now, and the stack trace was abbreviated. 
#1225

**Closed by mlazos** 2022-09-22 00:26 UTC
