### ISSUE TITLE
Support partially dynamic shapes

### ISSUE THREAD

**Issue by jansel** [pytorch/torchdynamo#38] opened 2022-03-12 17:11 UTC
In [update 5](https://dev-discuss.pytorch.org/t/torchdynamo-update-5-improved-capture-bigger-graphs/556) we wrote:

Unfortunately, the problem of dynamic shapes is more complex than one might think. Enabling torchdynamo.config.dynamic_shapes will cause new graph breaks. Many models have code like `assert x.shape == (1,2,3)`, `if x.size(1) == 10`, `math.sqrt(x.shape[-1])`, etc. This Python code operating on integer shapes is the defacto way to express many things in PyTorch. With static shapes, TorchDynamo can constant-propagate this stuff away, however, with dynamic shapes it will break the graph.

My current thinking is a “partially specialized shapes” mode in TorchDynamo. The basic idea would be that all shape start as fully dynamic, but then TorchDynamo would convert a tensor’s shapes to be static when the user called Tensor.size() and passed the result to a non-PyTorch operation. This would allow dynamic shapes most of the time, but still allow bigger graphs when users operate directly on shapes as integers.

To implement an initial version of this:

First build the analysis to add a `TensorVariable().input_sources: Set[Source]`.
```
def foo(a, b):
  c = a + b
```
In this example:
- a.input_souces = {a.source}
- b.input_souces = {b.source}
- c.input_souces = {a.source, b.source}

This is just a straight forward data flow analysis where sources are combined.  It looks similar to the [shape propagation currently implemented in TensorVariable.create](https://github.com/facebookresearch/torchdynamo/blob/fb2ab8ff722d254f7a4248ed5f01949451cebd08/torchdynamo/variables/tensor.py#L67).

Next, split [GuardBuilder.TENSOR_MATCH](https://github.com/facebookresearch/torchdynamo/blob/fb2ab8ff722d254f7a4248ed5f01949451cebd08/torchdynamo/guards.py#L282) into `TENSOR_MATCH_STATIC` and `TENSOR_MATCH_DYNAMIC`.  The underlying [TensorGuards](https://github.com/facebookresearch/torchdynamo/blob/fb2ab8ff722d254f7a4248ed5f01949451cebd08/torchdynamo/guards.py#L333) object implemented in C++ already has these two modes, so it just requires having the generated code have two instances of that object.

Finally, modify how [TensorVariable handles shape specialization](https://github.com/facebookresearch/torchdynamo/blob/fb2ab8ff722d254f7a4248ed5f01949451cebd08/torchdynamo/variables/tensor.py#L134).  Defer setting TensorVariable().size and TensorVariable().stride until [the user calls Tensor.size()](https://github.com/facebookresearch/torchdynamo/blob/fb2ab8ff722d254f7a4248ed5f01949451cebd08/torchdynamo/variables/tensor.py#L193).  Note there are a few different ways to get the size, so search for usages of `TensorVariable.size`.

When .size is called, add a new guard for TENSOR_MATCH_STATIC on all the input_sources.  (You can remove the now redundant TENSOR_MATCH_DYNAMIC guard in guard codegen.)

This should give you something that works and passes tests.

Improvements initial prototype:
- We need to handle dynamic shape ops like `nonzero`, `where`, `repeat`, etc.  Modify the analysis to mark tensors flowing from these ops, and break the graph if the user calls size on them.  You can [search for config.dynamic_shapes](https://github.com/facebookresearch/torchdynamo/blob/fb2ab8ff722d254f7a4248ed5f01949451cebd08/torchdynamo/variables/tensor.py#L223) to find where we currently conditionally break the graph on those ops.
- If a user passes the size directly to another PyTorch op, for example `torch.empty(x.size())` we don't need to shape specialize and can just put the call to .size() in the graph.  Similarly, simple math ops on sizes can be included in the graph.  To handle this we will need a SizeVariable() to track and decide what can go in the graph and what requires specialization.
- We don't need to specialize every dimension if the user code only uses some dimensions.  We need better shape analysis to make this happen though.  @eellison might be able to provide pointers for better shape analysis.

cc @ezyang

**Comment by jansel** [comment] 2022-03-12 17:31
cc @Krovatkin

**Comment by eellison** [comment] 2022-03-15 17:57
Just throwing out another idea without too much consideration of difficulty of implementation vs value added - if we have fast separably computable shape functions implemented for operators, it should be eventually possible to do things like compute `math.sqrt(x.shape[-1])` from the sizes of inputs and pass that in as a computed value into the graph so that backends do not need to compute themselves (regardless of if `x` is an input or not). Similarly you might eventually be able to specialize something like `if x.size(1) == 10` from the inputs of the prior block.

**Comment by jansel** [comment] 2022-03-22 21:57
Dropping a link to @ezyang's notebook here: https://github.com/albanD/subclass_zoo/blob/64cfc6bd670f79b260492f0ecbbda15a50c4fa9c/torchdynamo_dynamic_inference.ipynb

**Comment by ezyang** [comment] 2022-03-24 18:59
@mruberry, @ngimel and @zdevito were discussing this last night, and the model here seems to result in hard-to-fix overspecialization when implementing broadcasting in userland.

Broadcasting typically looks something like this:

```
def bad_assert_shape_broadcast(lhs, rhs):
    r = []
    for x, y in itertools.zip_longest(
        reversed(lhs.shape), reversed(rhs.shape), fillvalue=1
    ):
        if x == 1:
            r.append(y)
        elif y == 1:
            r.append(x)
        elif x == y:
            r.append(x)
        else:
            raise RuntimeError("shapes not compatible")
    return tuple(reversed(r))
```

where we go through the sizes and check if they are 1 (if so, that means we broadcast that input), otherwise we require the results to be equal.

The problem is that all of these conditions on `x == 1` and `x == y` will force the transitive set of dependencies to be static. This means even if I run a simple program `add(x, y)` with `x: (4,)` and `y: (1,)`, x will be forced to be static (because we tested if it was one before testing if y was one). Furthermore, if I have `add(x, y)` with `x: (4,)` and `y: (4,)`, I will specialize both x and y because I had to do the `x == y` test (but actually, what I'd like a more subtle guard that just requires x and y to have the same shape)

**Comment by jansel** [comment] 2022-03-24 21:59
@ezyang do we have motivating examples besides broadcasting?  Or is it just broadcasting?

If it is just broadcasting, then "==1"/"!=1" specialization would get us close.  We are already doing forms of that elsewhere, so it might be possible to build a robust "oneness" analysis pass.   That does not handle the `if x==y` case though.

Perhaps we just need to bite the bullet and add symbolic shape formulas for all ops then use a solver like Z3 to statically reason about what guards are needed to guarantee certain paths through control flow in the user program.  I hesitate to start there (due to the complexity), but I feel like that is where we eventually may end up.

**Comment by ezyang** [comment] 2022-03-24 22:15
> @ezyang do we have motivating examples besides broadcasting? Or is it just broadcasting?

There are other dumb cases like reshape returning a view/copy depending on the strides of the input. I think I'm mostly interested in a meta solution where I don't have to reason about every case individually. @zdevito and I talked about this and we think there is a simple way to sidestep the complexity.

We entered this exercise from the perspective of "we want to try to make our input shapes maximally dynamic". But in the real world this is going to end up doing a lot of work that is actually unnecessary when the input shapes are mostly static. If everything in our input is static, all of the analysis we are doing here is unnecessary, because all of the internal conditions are going to go the same way every time.

So, what we should do is *optimistically* assume that everything is static, and then pessimistically decay things to dynamic when (1) the user tells us so or (2) we observe it in reality. For static inputs, we can handle conditions just fine. For dynamic inputs, it seems very reasonable to just graph break whenever a user explicitly depends on a condition derived from the dynamic input. We still need symbolic shape formulas, but we don't need to do fancy backward analysis from Z3, we just need to know if a condition depended on a dynamic shape (tracking sizes per dim will help precision and avoid unnecessary graph breaks). And the graph breaks will occur *precisely* when we need divergent behavior for the dynamic inputs as specified by the user.

This is all under the assumption that we want to avoid having to add bailouts to torchdynamo, which I know you've said you're willing to do, but it seemed to us like it would be a lot of work to do so. Bailouts in their simplest form don't need Z3 but you have to spend work executing enough logic to get up to the bailout, and you do need Z3 if you want to simplify the residual bailout program...

**Comment by zdevito** [comment] 2022-03-24 22:32
The ordering of the decisions can also be flipped around giving something like:

* A dimension value never affects python execution -> no need to specialize

* A dimensions does affect python execution:

    * It is observed as static -> specialize

    * it is observed as changing -> graph break   

However, primitive decomposition will add additional places where we have to make a size-based decision in rare cases. Also if we know a static size, compilers will have to do less work when further specializing for sizes (e.g. in tuning a matmul). So there is some value in 'assume static' until proven otherwise going first.

**Comment by jansel** [comment] 2022-03-24 23:03
I like that idea, and pretty close to what I suggested -- with the addition of adding a backoff-to-graph-breaking heuristic on the N-th recompile (where N=2).

Bailouts wouldn't be that hard at the TorchDynamo level, however compiler backends don't support them.  Bailouts would also help in the case of data-dependent control flow, and remove the need for a graph break in those cases.   Tracing-JIT style.  @csarofeen any interest in adding bailout support to nvFuser.

**Comment by Krovatkin** [comment] 2022-03-30 17:42
I was wondering if we could maybe try to break up these requirements for supporting dynamic shapes by layer (OSI-style). I'd appreciate if you could fill in/correct me either inplace (if github allows) or in a separate comment.

Layer 1 : Tracing <--- what we are currently building @ezyang @zou3519
    * we want to trace shapes being used as arguments in ops symbolically and arithmetics on ops
         * this tells us how shapes are used and if there 
    * we want to materialize or propagate shapes if they are used in CF since we need to know what to trace next
    * trace comparisons to help a compiler make specialization decisions (I assume TD can't see backward graphs w/o tracing)?
Layer 2 : Compiling (Graph Compiler)
Layer 2.1 : Symbolic Shape Analysis @jansel @eellison
    * we want a facility to propagate constraints on a given dimension back to the inputs (needed for guards and for bailouts optimization if we were to use the latter)
Layer 2.2: Guarding @jansel
    * at the very least, we want to know what to guard on, so we can be correct?
        * if a shape is used in comparison and doesn't have dynamic ops upstream (e.g. nonzero, unique), we can guard on a set of input dimensions contributing to this shape
        * if a shape is used in comparison and is dynamic upstream, we need to break a graph or use bailouts?
    * the shapes we must guard on we can specialize in a graph (may also be done in Layer 2.2)

Layer 2.2: (Device Compiler via TorchScript)
   * NVFuser
      * we may choose to overspecialize based on profiling information from inputs
      * @csarofeen @jjsjann123
Layer 3 : Runtime @jansel 
   * we want to figure out what to do when guards fail. It sounds like we have different types of guard failures
         * must guards that guarantee we are correct
         * overspecialized guards that were used for optimization
         * bailouts?

**Comment by eellison** [comment] 2022-03-30 22:11
> were discussing this last night, and the model here seems to result in hard-to-fix overspecialization when implementing broadcasting in userland.

If we specialize based on Symbolic Value Sets and 1s, something like:

```
        if x == 1:
            r.append(y)
        elif y == 1:
            r.append(x)
        elif x == y:
            r.append(x)
        else:
            raise RuntimeError("shapes not compatible")
```
can be optimized out without requiring overspecialization

**Comment by jjsjann123** [comment] 2022-04-04 21:19
> Enabling torchdynamo.config.dynamic_shapes will cause new graph breaks. Many models have code like assert x.shape == (1,2,3), if x.size(1) == 10, math.sqrt(x.shape[-1]), etc. This Python code operating on integer shapes is the defacto way to express many things in PyTorch. With static shapes, TorchDynamo can constant-propagate this stuff away, however, with dynamic shapes it will break the graph.

Have we actually observed performance hit from graph breaking on dynamic-shape-based control flow in a real model? In the update post (https://dev-discuss.pytorch.org/t/torchdynamo-update-5-improved-capture-bigger-graphs/556), sounds like getting basic dynamic shape support (assuming all tensors to be dynamic shape and breaking on dynamic-shape-based control flow) would be good enough to cover current workflows. Our assumption is that the majority of the models, especially models used in production, would be performing with the limited dynamic shape support despite graph fragmentation from dynamic-shape-based control flow.
I'm very hesitant going into guarding logic backed by complex analysis, they can lead to nasty debugging session, where it is tricky for user to trace the guard failure back the script. Bailout is simply not in our roadmap.

>Layer 2.2: (Device Compiler via TorchScript)
NVFuser
we may choose to overspecialize based on profiling information from inputs

I think it's fine for compiler backends to choose to further specialize on dynamic shapes. The added complication is tricky to debug but that's a reasonable choice to defer to backends. @Krovatkin 

>So, what we should do is optimistically assume that everything is static, and then pessimistically decay things to dynamic when (1) the user tells us so or (2) we observe it in reality. For static inputs, we can handle conditions just fine. For dynamic inputs, it seems very reasonable to just graph break whenever a user explicitly depends on a condition derived from the dynamic input. We still need symbolic shape formulas, but we don't need to do fancy backward analysis from Z3, we just need to know if a condition depended on a dynamic shape (tracking sizes per dim will help precision and avoid unnecessary graph breaks). And the graph breaks will occur precisely when we need divergent behavior for the dynamic inputs as specified by the user.

@ezyang's idea sounds appealing. Giving user the power to mark static/dynamic shape on inputs and graph breaking on dynamic-size-based control-flow.
I prefer a different angle to this, and take dimensions to be dynamic by default (unless user specifically told us otherwise). The rest would be the same, we'll just let graph break when control flows are encountered.

This allows us to progressively expand our support.
1. Initially we can just restrict the support to `everything being dynamic` and `graph breaking on dynamic control flow`;
2. We would allow user to specify static shape on certain dimensions and propagate the `static-ness` on symbolic shape formulas;
This allows us to slowly build out the symbolic shape formulas as we proceed, while maintaining support to dynamic shapes. The good things about this approach is that: 1. it does NOT require a heavy initial investment; 2. it pays back and resolves our issue with dynamic shape on existing work flow.

The problem is that it is still uncertain that dynamic-size-based control flow have any impact on real world models. Trying to optimize prematurely with made-up examples might give us a complex system that is very challenging to refactor later in the road.

**Comment by jansel** [comment] 2022-04-04 23:32
At least for the discussion here, I think the main source of dynamic-size-control-flow would be PrimTorch.  The idea of PrimTorch would be to move broadcasting checks to Python, so even the simple case of `a+b` would have dynamic-size-control-flow from inside the decomposed `torch.add` when it checks for broadcasts.

If PrimTorch does that (not everyone is convinced on this), we will need to get really good at handling dynamic-size-control-flow because almost every op will have it.

If we decide against that for PrimTorch, I think a much simpler solution will suffice.  We just need to make sure it handles the simple cases like `assert x.shape==(1,2,3)`, and graph break on anything complicated.

**Comment by ezyang** [comment] 2022-04-05 02:13
> I prefer a different angle to this, and take dimensions to be dynamic by default (unless user specifically told us otherwise)

Can we try to write down the tradeoffs for the various choices, static versus dynamic by default? I want to defer to your intuition as a backend writer but I am not seeing the case for dynamic by default. Maybe you are weighing instant quiescence a lot more than I am. Here's what I see.

Pro static by default:
* Automatic promotion from static to dynamic is always sound, but not vice versa: even if we observe an input to always take the same shape a hundred times, it could vary on the 101st time. 
* Upon quiescence (i.e., all dynamic inputs have been found), we will have found maximal length graphs (if inputs are dynamic are default, you will have maximally conservative graph chunks, leaving performance on the table until a user annotates inputs as static to recover larger graphs). In particular, by default, userland control flow on otherwise static graphs will not cause graph breaks.

Pro dynamic by default:
* No quiescence period is necessary; you will never have to recompile after the first compilation.
* No dynamic shape analysis is initially needed, since everything is dynamic and so you have to cut everywhere anyway. (But with static by default you can still do an easy conservative analysis; e.g., by tracking only Tensor level dependency as jansel suggests at the start of this point, for propagating dynamic-ness)

Am I missing anything?

BTW, for PrimTorch decompositions, even if they are not handled by the torchdynamo frontend (so we capture broadcasting torch.add from torchdynamo), we still need a second level specialization policy to actually run the lowerings (which are going to expect to be able to do, e.g., 1-size tests to insert appropriate broadcasts), so even if you don't need a policy for the first level specialization (user land Python only), we still need the policy for the second level.

**Comment by jjsjann123** [comment] 2022-04-05 09:55
> Pro static by default:
> - Automatic promotion from static to dynamic is always sound, but not vice versa: even if we observe an input to always take the same shape a hundred times, it could vary on the 101st time.
> - Upon quiescence (i.e., all dynamic inputs have been found), we will have found maximal length graphs (if inputs are dynamic are default, you will have maximally conservative graph chunks, leaving performance on the table until a user annotates inputs as static to recover larger graphs). In particular, by default, userland control flow on otherwise static graphs will not cause graph breaks.

> Pro dynamic by default:
> - No quiescence period is necessary; you will never have to recompile after the first compilation.
> - No dynamic shape analysis is initially needed, since everything is dynamic and so you have to cut everywhere anyway. (But with static by default you can still do an easy conservative analysis; e.g., by tracking only Tensor level dependency as jansel suggests at the start of this point, for propagating dynamic-ness)

This sounds about right to me and I can see the appeal of taking static by default, which automatically gives a tighter set of dynamic dimensions.

I was backing dynamic by default because:
1. It doesn't introduce debugging complexity. Dynamic by default means a naive user wouldn't be surprised by unintentional graph change, nor would it be necessary to navigate through nested fallback graph.

2. Re Pro dynamic by default point 2 [no dynamic shape analysis is initially needed]
At day-1 we don't need to do much more than breaking graph at dynamic-size-based control flow. My naive optimism is betting on that'll be enough to solve existing problems. I don't think this advantage has been given its deserved credit.
Even when we build out the system, dynamic by default sounds more robust to propagation failures. e.g. when static shape propagation fails, we'll ended up with graph breaking. Say if we have N point of shape properties set wrong, we'll ended up with o(N) fragmented graph, which is bad.
Comparing to static by default, for N point of dynamic dimension marked wrong, our fallback would each initially identify all shapes within the subgraph as static and trigger another propagation failure in the following run, which gives us o(N**2) materialized fallback. This is much worse.

I do realize that a large chunk of my argument is speculating on future implementation. :stuck_out_tongue_closed_eyes: Maybe a middle ground would be to give this as an option to user? In my naive mind, the main challenge in implementation would be the propagation of shape properties (static/dynamic) and I think they could share the same formula. So it's a decision that we don't have to make today.

**Comment by anijain2305** [comment] 2022-12-29 23:00
@ezyang Is this issue still valid after Dynamic shapes work?

**Comment by ezyang** [comment] 2022-12-30 00:18
That is a complicated question, as what we ended up implementing diverges a bit from jansel's initial proposal here. Let me see if there's anything here worth still thinking about.

When dynamic=True, we do dynamic by default, except parameters, which are assumed to be static by default, so we quiesce immediately. We don't do jansel's sledgehammer approach of making an input completely static when a user conditions on it; instead, we record the minimal guard condition necessary for the conditional in ShapeEnv, and instead have more complicated guard expressions to test at entry time. In particular, the use of SymInt in fake tensor completely bypasses the traditional TensorVariable specialization mechanism (however, we haven't removed the old specialization mechanism yet).

Sure, let's close this.

**Closed by ezyang** 2022-12-30 00:18 UTC
Labels: enhancement, dynamo
