### ISSUE TITLE
TIMM model failures:  view size is not compatible with input tensor's size and stride

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#1135] opened 2022-09-06 19:56 UTC
[Edited]
Repro:
```
benchmarks/timm_models.py -dcuda --inductor --float32 --train --accuracy --only coat_lite_min
benchmarks/timm_models.py -dcuda --inductor --float32 --train --accuracy --only volo_d1_224
```

Error:
```
Traceback (most recent call last):
  File "/fsx/users/binbao/torchdynamo-tip/benchmarks/common.py", line 1210, in run_one_model
    new_result = optimized_model_iter_fn(model, example_inputs)
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "benchmarks/timm_models.py", line 308, in forward_and_backward_pass
    def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
  File "benchmarks/timm_models.py", line 309, in <graph break in forward_and_backward_pass>
    cloned_inputs = clone_inputs(inputs)
  File "benchmarks/timm_models.py", line 312, in <graph break in forward_and_backward_pass>
    pred = mod(*cloned_inputs)
  File "/fsx/users/binbao/pytorch-release/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fsx/users/binbao/conda/envs/release/lib/python3.8/site-packages/timm/models/mlp_mixer.py", line 321, in forward
    def forward(self, x):
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "/fsx/users/binbao/pytorch-release/functorch/functorch/_src/aot_autograd.py", line 889, in forward
    return compiled_f(
  File "/fsx/users/binbao/pytorch-release/functorch/functorch/_src/aot_autograd.py", line 875, in new_func
    compiled_fn = create_aot_dispatcher_function(
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/utils.py", line 75, in time_wrapper
    r = func(*args, **kwargs)
  File "/fsx/users/binbao/pytorch-release/functorch/functorch/_src/aot_autograd.py", line 450, in create_aot_dispatcher_function
    aot_dispatch_autograd(flat_fn, fake_flat_tensor_args, aot_config)
  File "/fsx/users/binbao/pytorch-release/functorch/functorch/_src/aot_autograd.py", line 316, in aot_dispatch_autograd
    fx_g = make_fx(functionalize(fake_fn), aot_config.decompositions)(*joint_inputs)
  File "/fsx/users/binbao/pytorch-release/torch/fx/experimental/proxy_tensor.py", line 621, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer), tracer=fx_tracer, concrete_args=tuple(phs))
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "/fsx/users/binbao/pytorch-release/torch/fx/experimental/proxy_tensor.py", line 391, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "/fsx/users/binbao/pytorch-release/torch/fx/_symbolic_trace.py", line 739, in trace
    (self.create_arg(fn(*args)),),
  File "/fsx/users/binbao/pytorch-release/torch/fx/_symbolic_trace.py", line 614, in flatten_fn
    tree_out = root_fn(*tree_args)
  File "/fsx/users/binbao/pytorch-release/torch/fx/experimental/proxy_tensor.py", line 405, in wrapped
    out = f(*tensors)
  File "/fsx/users/binbao/pytorch-release/functorch/functorch/_src/eager_transforms.py", line 1420, in wrapped
    func_outputs = func(*func_args, **func_kwargs)
  File "/fsx/users/binbao/pytorch-release/functorch/functorch/_src/aot_autograd.py", line 309, in fake_fn
    return fx_g(primals, tangents)
  File "/fsx/users/binbao/pytorch-release/torch/fx/graph_module.py", line 658, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/fsx/users/binbao/pytorch-release/torch/fx/graph_module.py", line 277, in __call__
    raise e
  File "/fsx/users/binbao/pytorch-release/torch/fx/graph_module.py", line 267, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/fsx/users/binbao/pytorch-release/torch/fx/_symbolic_trace.py", line 717, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "/fsx/users/binbao/pytorch-release/torch/fx/experimental/proxy_tensor.py", line 357, in call_module
    return forward(*args, **kwargs)
  File "/fsx/users/binbao/pytorch-release/torch/fx/_symbolic_trace.py", line 710, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "/fsx/users/binbao/pytorch-release/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "<eval_with_key>.4", line 38, in forward
    view_2 = torch.ops.aten.view.default(getitem_5, [12544, 384]);  getitem_5 = None
  File "/fsx/users/binbao/pytorch-release/torch/_ops.py", line 60, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
```

**Comment by desertfire** [comment] 2022-09-06 19:58
According to @Chillee , this is a recent regression.

Also, https://github.com/pytorch/torchdynamo/pull/1028 is hitting a lot similar errors. We should fix it and and add TIMM to CI.

**Comment by desertfire** [comment] 2022-09-06 20:15
`git bisect` points to https://github.com/pytorch/torchdynamo/pull/1122 as the culprit.

**Comment by anijain2305** [comment] 2022-09-07 20:02
Repro

~~~

import torch
import torchdynamo
from torch import tensor, device
import torch.fx as fx
from torchdynamo.testing import rand_strided
from math import inf
from torchdynamo.debug_utils import run_fwd_maybe_bwd


from torch.nn import *
class Repro(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.self_blocks_0__norm = LayerNorm((256,), eps=1e-06, elementwise_affine=True)
        self.self_blocks_0__mlp_channels_fc1 = Linear(in_features=256, out_features=1536, bias=True)



    def forward(self, self_blocks_0__mlp_channels_act, self_stem_norm):
        self_blocks_0__norm = self.self_blocks_0__norm(self_stem_norm);  self_stem_norm = None
        self_blocks_0__mlp_channels_fc1 = self.self_blocks_0__mlp_channels_fc1(self_blocks_0__norm);  self_blocks_0__norm = None
        return (self_blocks_0__mlp_channels_act,)


mod = Repro().cuda()
opt_mod = torchdynamo.optimize("inductor")(mod)


args = [((64, 196, 1536), (301056, 1536, 1), torch.float32, 'cuda', True), ((64, 196, 256), (50176, 1, 196), torch.float32, 'cuda', True)]
args = [rand_strided(sh, st, dt, dev).requires_grad_(rg) for (sh, st, dt, dev, rg) in args]


with torch.cuda.amp.autocast(enabled=False):
    ref = run_fwd_maybe_bwd(mod, args)
    res = run_fwd_maybe_bwd(opt_mod, args)
    
~~~

**Comment by Chillee** [comment] 2022-09-07 20:45
I think this is caused by removing some decomposition from `_unsafe_view` to reshape.

**Comment by Chillee** [comment] 2022-09-10 01:07
Resolved by https://github.com/pytorch/pytorch/pull/84801

**Comment by eellison** [comment] 2022-09-21 19:16
This is fixed as of https://github.com/pytorch/pytorch/pull/85417 (sorry will try to land it now lol)

**Comment by ngimel** [comment] 2022-09-21 22:33
I've checked the first one on pytorch at 2386cd2945 (from 9/15) and it passes

**Comment by desertfire** [comment] 2022-09-22 15:11
There are still two cases failed, see the updated Repro instruction, cc @eellison

**Comment by eellison** [comment] 2022-09-22 15:21
Those don't repro for me anymore as of https://github.com/pytorch/pytorch/pull/85417

**Comment by anijain2305** [comment] 2022-09-26 17:09
@eellison This is the repro. Assigning to you for now, but feel free to assign somebody else.

Repro

~~~

import torch
import torchdynamo
from torch import tensor, device
import torch.fx as fx
from torchdynamo.testing import rand_strided
from math import inf
from torchdynamo.debug_utils import run_fwd_maybe_bwd


from torch.nn import *
class Repro(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.self_serial_blocks1_0__factoratt_crpe_qkv = Linear(in_features=64, out_features=192, bias=True)



    def forward(self, getitem_3, getitem_4, matmul_1, self_serial_blocks1_0__norm1):
        self_serial_blocks1_0__factoratt_crpe_qkv = self.self_serial_blocks1_0__factoratt_crpe_qkv(self_serial_blocks1_0__norm1);  self_serial_blocks1_0__norm1 = None
        softmax = getitem_3.softmax(dim = 2);  getitem_3 = None
        transpose_3 = softmax.transpose(-1, -2);  softmax = None
        matmul = transpose_3 @ getitem_4;  transpose_3 = getitem_4 = None
        return (matmul_1,)


mod = Repro().cuda()
opt_mod = torchdynamo.optimize("inductor")(mod)


args = [((2, 8, 3137, 8), (602304, 8, 192, 1), torch.float32, 'cuda', True), ((2, 8, 3137, 8), (602304, 8, 192, 1), torch.float32, 'cuda', True), ((2, 8, 3137, 8), (200768, 25096, 8, 1), torch.float32, 'cuda', True), ((2, 3137, 64), (200768, 64, 1), torch.float32, 'cuda', True)]
args = [rand_strided(sh, st, dt, dev).requires_grad_(rg) for (sh, st, dt, dev, rg) in args]


with torch.cuda.amp.autocast(enabled=False):
    ref = run_fwd_maybe_bwd(mod, args)
    res = run_fwd_maybe_bwd(opt_mod, args)
~~~

**Comment by eellison** [comment] 2022-09-26 17:34
This repros even without using fake tensor - because of the decomposition called in proxy_tensor.py for `_reshape_alias` - and also looks like `_reshape_alias` ignores the strides that are passed in. CC @Chillee (blame pointed me here)

**Comment by anijain2305** [comment] 2022-09-28 01:08
Assigning to myself so that I can learn more about this. This is not inductor problem and seems like decomp problem, latest repro

~~~

import torch
import torchdynamo
from torch import tensor, device
import torch.fx as fx
from torchdynamo.testing import rand_strided
from math import inf
from torchdynamo.debug_utils import run_fwd_maybe_bwd


from torch.nn import *
class Repro(torch.nn.Module):
    def __init__(self):
        super().__init__()



    def forward(self, permute_2, mul):
        softmax = mul.softmax(dim = -1)
        matmul = softmax @ permute_2
        return (matmul,)


mod = Repro().cuda()
opt_mod = torchdynamo.optimize("aot_inductor_debug")(mod)


args = [((2, 6, 196, 9, 32), (338688, 56448, 1, 196, 1764), torch.float32, 'cuda', True), ((2, 6, 196, 9, 9), (95256, 81, 486, 9, 1), torch.float32, 'cuda', True)]
args = [rand_strided(sh, st, dt, dev).requires_grad_(rg) for (sh, st, dt, dev, rg) in args]


with torch.cuda.amp.autocast(enabled=False):
    ref = run_fwd_maybe_bwd(mod, args)
    res = run_fwd_maybe_bwd(opt_mod, args)
~~~

**Comment by anijain2305** [comment] 2022-09-28 05:48
The issue seems to be that `softmax` decomp does not respect strides. Comparison between the two

~~~

import torch


from torchdynamo.testing import rand_strided

# Copied from decomps
import torch._prims_common as utils
def _softmax(x: torch.Tensor, dim: int, half_to_float: bool):
    if half_to_float:
        assert x.dtype == torch.half
    computation_dtype, result_dtype = utils.elementwise_dtypes(
        x, type_promotion_kind=utils.ELEMENTWISE_TYPE_PROMOTION_KIND.DEFAULT
    )
    x = x.to(computation_dtype)
    x_max = torch.amax(x, dim, keepdim=True)
    unnormalized = torch.exp(x - x_max)
    result = unnormalized / torch.sum(unnormalized, dim, keepdim=True)
    if not half_to_float:
        result = result.to(result_dtype)
    return result



args = [((2, 6, 196, 9, 9), (95256, 81, 486, 9, 1), torch.float32, 'cuda', True), ]
args = [rand_strided(sh, st, dt, dev).requires_grad_(rg) for (sh, st, dt, dev, rg) in args]
x = args[0]


ref = torch.ops.aten._softmax(x, -1, False)
res = _softmax(x, -1, False)


assert ref.stride() == res.stride()
~~~

**Comment by anijain2305** [comment] 2022-09-28 18:34
This error should be fixed by https://github.com/pytorch/pytorch/pull/85788 and then fails on accuracy .. sigh ...
But that seems like an inductor issue because `aot_inductor_debug` backend is passing end2end.

**Closed** 2022-09-28 21:10 UTC
Labels: inductor, vertical:timm
