### ISSUE TITLE
[Inductor] [CPU] Crash failure in timm model swsl_resnext101_32x16d

### ISSUE THREAD

**Issue by chuanqi129** [pytorch/torchdynamo#1880] opened 2022-11-17 08:23 UTC
### 🐛 Describe the bug

This failure was found in latest **TorchInductor CPU Performance Dashboard** refresh test in https://github.com/pytorch/torchdynamo/issues/1617#issuecomment-1316633340

SW information

SW	| Nightly commit	| Master/Main commit
----|--------|-----
Pytorch	|[637228b](https://github.com/blzheng/pytorch/commit/637228bcc4d2566fb617bbf1c4abeff69b3bdae7)	|[46796fe](https://github.com/blzheng/pytorch/commit/46796fe5e9b74602d45927304773fdcda1c3215a)
Torchbench|	/	|[022dfe3](https://github.com/pytorch/benchmark/commit/022dfe3d89db9278119bf1cd179997076b5ec5b5)
torchaudio	|[4b10b6a](https://github.com/pytorch/audio/commit/4b10b6adece473ad70e221bb3f9442d11906111f)	|[74f9a89](https://github.com/pytorch/audio/commit/74f9a894fcd4e7d635919803b364e47577a2b6e8)
torchtext	|[71e4561](https://github.com/pytorch/text/commit/71e456119d39cf72a511ce6acb10b737e02102d3)	|[c047efe](https://github.com/pytorch/text/commit/c047efeba813ac943cb8046a49e858a8b529d577)
torchvision	|[797e1ac](https://github.com/pytorch/vision/commit/797e1acf043621c5b53319032a269cbe1190b018)	|[ffd5a56](https://github.com/pytorch/vision/commit/ffd5a567eb90abf6b5555063da434d3c130d540f)

detail info reference the [Dashboard](https://github.com/pytorch/torchdynamo/issues/1617#issuecomment-1316633340) 

### Error logs

`ERROR:common:Failed for dynamo expected size 512==512, stride 1==3136 at dim=1`

### Minified repro

`python benchmarks/dynamo/timm_models.py --performance --float32 -dcpu -n50 --inductor  --no-skip --dashboard --only=swsl_resnext101_32x16d --batch_size 1 `

**Comment by eellison** [comment] 2022-11-17 21:24
Appears to be dupe of https://github.com/pytorch/torchdynamo/issues/1880

**Comment by eellison** [comment] 2022-11-17 21:25
Hi, @chuanqi129, thank you for opening the issues. I could not repro this on master. Can you please submit a minified repro ?

**Comment by eellison** [comment] 2022-11-17 21:31
This doesn't repro on master for me. Please try a more recent nightly commit and re-open if you are still seeing the error.

**Closed by eellison** 2022-11-17 21:31 UTC
Labels: bug, cpu

**Comment by chuanqi129** [comment] 2022-11-18 01:45
Thanks @eellison  for your quick response. We're testing the recent nightly commit to refresh the Inductor CPU performance dashboard (twice per week), and will update if we still meet some issues. And also thanks for your guide, we'll classify the failures in advance in the future to avoid a lot of duplicate issues.

**Comment by eellison** [comment] 2022-11-18 18:15
@chuanqi129 thank you, we appreciate the issues ! If you submit with a minified repro it's more likely that someone will fix it quickly! We appreciate that. Thank you. See, minifier [here](https://github.com/pytorch/torchdynamo/blob/main/documentation/TROUBLESHOOTING.md).

**Comment by chuanqi129** [comment] 2022-11-18 18:20
Thanks @eellison. Sure, We will study how to use it
